---
- hosts: base_ubuntu base_pi base_proxmox
  become: true
  pre_tasks:
    - name: Checking for outdated packages
      command: apt-get -y --dry-run upgrade
      changed_when: False
      register: check_upgrade
    - name: Show outdated packages
      debug:
        msg: "{{ check_upgrade.stdout_lines }}"
      when: "'packages will be upgraded' in check_upgrade.stdout"

  tasks:
    - name: Upgrade packages
      apt:
        upgrade: yes
      when: "'packages will be upgraded' in check_upgrade.stdout"
