---
# tasks file for roles/docker_base

- name: Ensure /opt/stacks is created
  ansible.builtin.file:
    path: /opt/stacks
    owner: kakapo
    mode: '0755'
    state: directory

- name: Ensure /opt/data is created
  ansible.builtin.file:
    path: /opt/data
    owner: kakapo
    mode: '0775'
    state: directory

- name: Ensure "primary" network exists
  community.docker.docker_network:
    name: primary
