---
# tasks file for roles/customise

- name: Install tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git-core
      - zsh
      - nano
      - htop
      - httpie
      - mosh
      - fd-find
      - zoxide
      - fzf
      - bat

- name: Install full Python tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-setuptools
      - python3-pip

- name: Set default editor to nano
  community.general.alternatives:
    name: editor
    path: /bin/nano

- name: Fetch nano syntax highlighting enhancements.
  git:
    repo: https://github.com/scopatz/nanorc.git
    dest: /usr/share/nano-syntax-highlighting/
    version: 2020.10.10

- name: Add includes to systemwide nanorc.
  blockinfile:
    path: /etc/nanorc
    marker: "## {mark} extended syntax highlighting"
    block: |
      include "/usr/share/nano-syntax-highlighting/yaml.nanorc"
      include "/usr/share/nano-syntax-highlighting/zsh.nanorc"
      include "/usr/share/nano-syntax-highlighting/nginx.nanorc"

- name: Better tabs for systemwide nanorc.
  blockinfile:
    path: /etc/nanorc
    marker: "## {mark} better tabs"
    block: |
        set tabsize 4
        set tabstospaces

- name: Remove old option from nanorc
  lineinfile:
   path: /etc/nanorc
   search_string: 'set suspend'
   state: absent

- name: Copy /etc/motd
  template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644

- name: Copy root .zshrc
  template:
    src: root_zshrc.j2
    dest: /root/.zshrc
    owner: root
    group: root
    mode: 0644

- name: Install lsiommu
  ansible.builtin.copy:
    src: lsiommu
    dest: /usr/local/bin
    owner: root
    group: root
    mode: a+x
