---
# tasks file for roles/common

- name: Add deploy user
  user: name={{ deploy_user }} password="{{ deploy_pass }}" shell=/bin/bash

- name: Add authorized keys for deploy user
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ lookup('file', deploy_key) }}"
    state: present
    exclusive: true

- name: Update APT package cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install tools required for deployment
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - sudo
      - python3-apt
      - aptitude

- name: Add deploy user to sudoers
  lineinfile: dest=/etc/sudoers
    regexp="{{ deploy_user }} ALL"
    line="{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL"
    state=present

- name: Disable PasswordAuthentication
  lineinfile: dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication no"
    state=present
  notify: Restart ssh

- name: Disable PermitEmptyPasswords
  lineinfile: dest=/etc/ssh/sshd_config
    regexp="^PermitEmptyPasswords"
    line="PermitEmptyPasswords no"
    state=present
  notify: Restart ssh
