---
# tasks file for roles/docker

- name: Install Prerequisites
  apt:
    name: ['apt-transport-https','ca-certificates', 'curl', 'software-properties-common']
    state: present
    update_cache: yes

- name: Add GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /etc/apt/keyrings/docker.gpg

- name: Configure Repository
  apt_repository:
    repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes
    filename: docker

- name: Install Docker
  apt:
    name: ['docker-ce','docker-ce-cli','containerd.io','docker-buildx-plugin','docker-compose-plugin']
    state: present
    update_cache: yes

- name: Add Deploy to Docker Group
  user:
    name: "deploy"
    groups: "docker"
    append: yes

- name: Add Kakapo to Docker Group
  user:
    name: "kakapo"
    groups: "docker"
    append: yes

- name: Add alias to global zshrc
  ansible.builtin.blockinfile:
      path: "/etc/zshrc"
      create: true
      owner: root
      mode: u=rw,g=r,o=r
      marker: "# {mark} ANSIBLE MANAGED DOCKER ALIAS"
      block: |
          alias ctop='docker run -it --rm --name ctop -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop:latest'
          alias update-docker='docker run --rm --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once'
          alias dc='docker compose'
          alias d='docker'
          alias upd='docker compose pull && docker compose up -d'

- name: Install Pip
  apt:
    update_cache: yes
    state: present
    name: python3-pip

- name: Install 'Docker SDK for Python'
  pip:
    name: docker


- name: Check if dive is installed
  package:
    name: dive
    state: present
  check_mode: true
  register: dive_installed

- name: Copy dive installer to remote machine
  when: dive_installed == 0
  ansible.builtin.copy:
    src: dive_0.11.0_linux_amd64.deb
    dest: /tmp/dive.deb
    mode: 0644

- name: Install dive
  when: dive_installed == 0
  ansible.builtin.apt:
    deb: /tmp/dive.deb

- name: Remove dive installer
  when: dive_installed == 0
  ansible.builtin.file:
    path: /tmp/dive.deb
    state: absent

- name: Disable IP in sysinfo
  ansible.builtin.copy:
    src: client.conf
    dest: /etc/landscape/client.conf
    owner: root
    group: root
    mode: 0644
